config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  root to: 'pages#home'
  resources :trips, only: [ :index, :create, :new, :show] do
    resources :bookings, only: [:new, :create]
    end
  resources :users, only: [:show] do
    member do
      get :dashboard
      end
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :description, presence: true
  validates :user_id, uniqueness: { scope: :trip_id,
    message: "already joined this trip" }
  belongs_to :user
  belongs_to :trip
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 30 }
  validates :destination, presence: true
  validates :budget_min, presence: true
  validates :budget_max, presence: true
  validates :departure_date, presence: true
  validates :return_date, presence: true
  validates :capacity, presence: true, numericality: { greater_than: 1 }
  validates :photo, presence: true
  validate :end_date_after_start_date # error message is not displayed yet in simple form
  include PgSearch::Model

  scope :undeparted, -> { where('departure_date > ?', Date.today) }
  scope :departed, -> { where('departure_date <= ?', Date.today) }
  pg_search_scope :search_by_destination, against: :destination, using: { tsearch: { prefix: true } }

  geocoded_by :destination
  after_validation :geocode, if: :will_save_change_to_destination?

  private

  def end_date_after_start_date
    return if return_date.blank? || departure_date.blank?

    if return_date < departure_date
      errors.add(:return_date, "must be after the departure date")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  has_many :bookings
  has_many :trips, through: :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :birth_date])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :birth_date, :description, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # def new
  #   @booking = Booking.new
  #   @trip = Trip.find(params[:trip_id])
  # end

  def create
    @user = current_user
    @booking = Booking.new(booking_params)
    @trip = Trip.find(params[:trip_id])
    @booking.trip = @trip
    @booking.user = @user
    if @booking.save
      redirect_to trip_path(@trip)
    else
      flash[:alert] = @booking.errors.full_messages.join("; ")
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @trips = Trip.geocoded # returns flats with coordinates
    @markers = @trips.map do |trip|
      {
        lat: trip.latitude,
        lng: trip.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { trip: trip })
      }
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @trips = Trip.search_by_destination(params[:query])
    else
      @trips = [Trip.undeparted.order(departure_date: :asc), Trip.departed].flatten
    end
  end

  def new
    @trip = Trip.new # needed to instantiate the form_for
  end

  def show
    @trip = Trip.find(params[:id])
    @booking = Booking.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    if @trip.save
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  private

  def trip_params
    params.require(:trip).permit(:title, :description, :destination, :budget_min, :budget_max, :capacity, :return_date, :departure_date, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @trips = Trip.all
    @user = current_user
    @trips_admin = @trips.where(user_id: @user.id)
  end

  def show
    @user = User.find(params[:id])
    @trips = @user.bookings.map do |booking|
        next booking.trip if booking.accepted == true && booking.trip.geocoded?
        nil
    end.compact
     @markers = @trips.map do |trip|
      {
        lat: trip.latitude,
        lng: trip.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { trip: trip })
      }
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container my-5">
  <div class="form p-5 m-3 bg-white">
    <h1>Thank you for choosing this trip!</h1>
    <%= simple_form_for [@trip, @booking ] do |f| %>
        <%= f.input :description, label: "Please tell us why you want to join this trip" %>
        <%= f.submit "Submit your application", class: "btn btn-travel mt-3" %>
      <% end %>
      <hr>
      <%= link_to 'Back', trips_path, class: "btn-travel-secondary" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-white">

  <%= image_tag "vgt logo1.png", alt: "logo", width: 180 %>
  <p>© 2020 Very Good Trip, Inc. All rights reserved</p>
  <div class="icons">
    <i class="fab fa-github"></i>
    <i class="fab fa-facebook-square"></i>
    <i class="fab fa-twitter"></i>
  </div>

</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'test1708.png' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?'}, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to 'Log in', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item active mr-3">
            <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li class="nav-item dropdown ml-3">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", width: 40, height: 40, gravity: :face, id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://icon-library.com/images/default-user-icon/default-user-icon-8.jpg", class: "avatar dropdown-toggle", width: 40, height: 40, crop: :fill, gravity: :face, id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "View my dashboard", dashboard_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "View my profile", user_path(current_user), class: "dropdown-item" %>
            </div>
          </li>
        <% end %>

      </ul>
    </div>
</div>

app/views/layouts/_tripcard.html.erb
<div class="card">
  <% if trip.photo.attached? %>
    <div class = "card-top d-flex align-items-center justify-content-center" style=" position: relative; height: 260px; background-size:cover; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path trip.photo.key%>')">
  <% else %>
    <div class = "card-top d-flex align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path('sf.jpg')%>); background-size: cover ; height: 260px; position: relative">
  <% end %>

  <h2 class="text-center p-2"><%= link_to trip.title, trip_path(trip), style: "text-decoration:none; color: white"%></h2>
  <% days_before_departure = trip.departure_date - Date.today %>

  <!-- Badges Departure -->
  <% if days_before_departure <= 0 %>
    <span class="badge badge-success mb-3 p-2 font-weight-light" style="position: absolute; right: 20px; top:20px;"> Departed !</span>
  <% elsif days_before_departure <= 7 %>
    <span class="badge badge-danger mb-3 p-2 font-weight-light" style="position: absolute; right: 20px; top:20px;"> <%= (days_before_departure).to_i %> days before departure</span>
  <% else %>
    <span class="badge badge-info mb-3 p-2 font-weight-light" style="position: absolute; right: 20px; top:20px;"> <%= (days_before_departure).to_i %> days before departure</span>
  <% end %>
  </div>
    <div class="card-body" style="position: relative">
     <!--  AVATARS -->
    <ul class= "in-line p-2" style="position: absolute; right: 17px; top:-28px ">

    <!-- TRIP OWNER -->
    <% if trip.user.photo.attached? %>
      <li class="list-inline-item"><%= cl_image_tag trip.user.photo.key, width: 40, height: 40, gravity: :face, class: "avatar" %></li>
    <% else %>
      <li class="list-inline-item"><%= image_tag "https://icon-library.com/images/default-user-icon/default-user-icon-8.jpg", width: 40, height: 40, crop: :fill, gravity: :face, class: "avatar" %></li>
    <% end %>

    <!-- TRIP USERS -->
    <% trip.bookings.each do |booking| %>
      <% if booking.accepted %>
        <% if booking.user.photo.attached? %>
          <li class="list-inline-item"><%= cl_image_tag booking.user.photo.key, width: 40, height: 40, gravity: :face, class: "avatar" %></li>
        <% else %>
          <li class="list-inline-item"><%= image_tag "https://icon-library.com/images/default-user-icon/default-user-icon-8.jpg", width: 40, height: 40, crop: :fill, gravity: :face, class: "avatar" %></li>
        <% end %>
      <% end %>
    <% end %>
    </ul>

    <!-- TRIP INFO -->
      <h5 class="card-title font-weight-bold"><%=trip.destination%></h5>
      <div class="card-bottom d-flex justify-content-between ">
       <p class="card-text card-text-description"><%=trip.description%></p>
       <div class="card-details ml-4">
        <p class="card-text"><small class="text-muted"><%=trip.capacity %> people max</small></p>
        <p class="card-text"><%= (trip.return_date - trip.departure_date).to_i %> nights</p>
        <p class="card-text font-weight-bold">$ <%=trip.budget_min%> - <%=trip.budget_max%></p>
       </div>
     </div>
   </div>
</div>

app/views/layouts/_tripcards.html.erb
<div class="cards">
  <div class="row">
    <% @trips.each do |trip| %>
      <div class="col-12 col-lg-6 p-3">
      <%= render 'layouts/tripcard', trip: trip  %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_tripcards_admin.html.erb
<div class="cards">
  <div class="row">
    <% @trips_admin.each do |trip| %>
      <div class="col-12 col-lg-6 p-3">
      <%= render 'layouts/tripcard', trip: trip  %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_tripcards_user.html.erb
<div class="cards">
  <div class="row">
    <% current_user.trips.each do |trip| %>
      <div class="col-12 col-lg-6 p-3">
      <%= render 'layouts/tripcard_user', trip: trip  %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Very Good Trip 🧳</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <!-- Devise alerts -->
    <%= render 'shared/flashes' %>
    <!-- Nav bar -->
    <%= render 'layouts/navbar' %>
    <div class="container-view">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_info_window.html.erb
<div class="container-card d-flex text-center align-items-center " style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path trip.photo.key %>')">
  <%= link_to trip.title, trip_path(trip), style: 'font-size: 14px;', class: 'p-2' %>
  <%#= cl_image_tag(trip.photo.key, :width=>200 , :height=> 100 , :crop=>"scale") %>
</div>

app/views/pages/home.html.erb
<div class="banner d-flex text-center align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path("banner-new.jpg") %>);">

  <div class="container">
    <h1>Welcome to <strong>Very Good Trip</strong>!</h1>
    <p>Travel to <span id="banner-typed-text"></span></p>
      <!-- SEARCHBAR -->
    <%= form_tag trips_path, class: 'my-5', method: :get do %>
      <div class="d-flex align-items-center justify-content-center">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          style: 'width: 500px; border-radius: 20px;',
          placeholder: "Type a destination..."
        %>
        <%= submit_tag "Search", class: "btn btn-travel-secondary ml-2" %>
      </div>
    <% end %>
    <%= link_to 'Create a trip', new_trip_path, class: 'btn btn-travel mt-2'  %>
  </div>

</div>

<div class="container">

  <h2 class="text-center mt-5 font-weight-bold">Why Very Good Trip?</h2>
  <div class="container text-center mt-4 mb-5">
    <div class="row">
      <div class="col-md-4 p-3">
        <%= image_tag "friend.png", width: 125, class: 'mb-3' %>
        <h4>Find travel buddies</h4>
        <p>Join a group with same interests to plan your next trip together</p>
      </div>
      <div class="col-md-4 p-3">
        <%= image_tag "travel.png", width: 125, class: 'mb-3' %>
        <h4>Travel all together</h4>
        <p>Explore amazing destinations all around the world</p>
      </div>
      <div class="col-md-4 p-3">
        <%= image_tag "fun.png", width: 125, class: 'mb-3' %>
        <h4>Amazing experiences</h4>
        <p>Enjoy your trip together and make friends for life</p>
      </div>
    </div>
  </div>

  <h2 class="text-center mt-5 pb-5 font-weight-bold">Find your next trip</h2>
  <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <div class="last-trips mt-5 mb-5">
    <h2 class="text-center mb-5 font-weight-bold">Or explore the latest trips</h2>
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= render 'layouts/tripcard', trip: Trip.last %>
        </div>
        <div class="carousel-item">
          <%= render 'layouts/tripcard', trip: Trip.last(2)[0] %>
        </div>
        <div class="carousel-item">
          <%= render 'layouts/tripcard', trip: Trip.last(3)[0] %>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/trips/index.html.erb
<div class="container bg-white p-5 my-5">
  <h1 class="text-center mb-5">Find the trip of your dreams 🤩</h1>
  <!-- SEARCHBAR -->
  <%= form_tag trips_path, class: 'mb-5', method: :get do %>
    <div class="d-flex align-items-center">
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        style: 'border-radius: 20px;',
        placeholder: "Type a destination..."
      %>
      <%= submit_tag "Search", class: "btn btn-travel ml-2" %>
    </div>
  <% end %>
  <!-- the list of movies -->
  <%= render 'layouts/tripcards' %>

  <hr>
  <div class="new-destination text-center mt-5 mb-5">
    <h2>Your perfect trip does not exist? Create it! 💪</h2>
    <%= link_to 'Add new destination', new_trip_path(@trip), class: 'btn btn-travel mt-3' %>
  </div>
</div>

app/views/trips/new.html.erb
<div class="container my-5">
  <div class="form p-5 m-3 bg-white">
    <h2 class="text-center mb-5">Create a new trip</h2>
    <%= simple_form_for [ @trip ] do |f| %>
      <%= f.input :title %>
      <%= f.input :description, as: :text %>
      <%= f.input :destination %>
      <div class="row">
        <div class="col">
          <%= f.input :budget_min %>
        </div>
        <div class="col">
          <%= f.input :budget_max %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= f.input :departure_date, as: :string %>
        </div>
        <div class="col">
          <%= f.input :return_date, as: :string %>
        </div>
      </div>
      <%= f.input :capacity %>
      <%= f.input :photo, as: :file, required: true %>
      <%= f.submit "Submit Trip", class: "btn-travel mt-3" %>
    <% end %>
    <hr>
    <%= link_to 'Back', trips_path, class: "btn-travel-secondary mt-2" %>
  </div>
</div>

app/views/trips/show.html.erb
<div class="container mt-5 show-container">
  <div class="image">
    <div class = "card-top d-flex flex-column align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @trip.photo.key, crop: :fill %>'); background-size: cover ; height: 400px;">
      <h2 class="text-center textbanner p-2 color:white"><%=@trip.title%></h2>
      <p class="text-white"><%= @trip.destination %></p>
    <%#= cl_image_tag @trip.photo.key, height: 300, width: 400, crop: :fill%>
    </div>
  </div>
  <div class="row p-1 destination">
    <h2>The trip</h2>
  </div>
  <div class="row p-4 description text-center" style="box-shadow:5px 5px 5px lightgrey;">
    <%= @trip.description %>
  </div>

<!--   <div class="option my-5 ">
    <div class="tag ">Hiking</div>
    <div class="tag mx-3">Adventure</div>
    <div class="tag ">English speaking</div>
 </div> -->

  <div class="spec mt-5 mb-3">
    <h2 class="text-center">Specs</h2>

    <div class="icons my-3">
      <div class= "icon text-center">
        <div style="font-size: 30px;">💵</div>
        <p class="bold text-center">Estimated</p>
        <p class="text-center">$<%= @trip.budget_min %> and $<%= @trip.budget_max %></p>
        </div>
      <div class= "icon text-center">
        <div style="font-size: 30px;">🛫</div>
        <p class="bold text-center">Departure date</p>
        <p class= "text-center"><%= @trip.departure_date.strftime('%e %B %Y') %></p>
      </div>
      <div class= "icon text-center">
        <div style="font-size: 30px;">🛬</div>
        <p class="bold text-center">Return date</p>
        <p class= 'text-center'><%= @trip.return_date.strftime('%e %B %Y') %></p>
      </div>
      <div class= "icon text-center">
        <div style="font-size: 30px;">👩‍👩‍👧‍👧</div>
        <p class="bold text-center">Capacity max</p>
        <p class="text-center"><%= @trip.capacity %> people</p>
      </div>
    </div>
  </div>


  <h2 class="text-center mt-5 mb-4"><strong>Meet your dream team</strong></h2>

<!--   Iteration over bookings to display user cards -->
 <!--  <div class="cards justify-content-center">
    <div class="card"> -->

    <!-- OWNER -->
  <div class="cards-product mt-5">
    <div class="card-product" style="position: relative;">
      <% if @trip.user.photo.attached? %>
        <%= cl_image_tag @trip.user.photo.key %>
      <% else %>
        <%= image_tag "https://icon-library.com/images/default-user-icon/default-user-icon-8.jpg" %>
      <% end %>
      <div class="card-product-infos">
        <span class="badge badge-dark mb-3 p-2 font-weight-light" style="position: absolute; right: 20px; top:20px;">Owner</span>
        <h2><%= @trip.user.first_name %></h2>
        <p><%= @trip.user.description %></p>
        <p><%= link_to "View profile", user_path(@trip.user) %>

      </div>
    </div>

    <!-- TRIP USERS -->
    <% @trip.bookings.each do |booking| %>
      <% if booking.accepted %>
        <div class="card-product">
        <% if booking.user.photo.attached? %>
            <%= cl_image_tag booking.user.photo.key %>
        <% else %>
            <%= image_tag "https://icon-library.com/images/default-user-icon/default-user-icon-8.jpg" %>
        <% end %>
          <div class="card-product-infos">
            <h2><%= booking.user.first_name %></h2>
            <p><%= booking.user.description %></p>
            <p><%= link_to "View profile", user_path(booking.user) %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class='text-center mt-5 mb-5'>
    <% accepted_applications = [] %>
    <% @trip.bookings.each do |booking| %>
      <% if booking.accepted == true %>
        <% accepted_applications << booking %>
      <% end %>
    <% end %>


    <% if @trip.user == current_user %>
      <a href="#" class="btn btn-travel-secondary mr-3">Manage the trip</a>
      <%= link_to 'Back to all trips', trips_path, class: "btn-travel mb-3" %>
    <% elsif @trip.departure_date < Date.today %>
      <p> They are already gone! </p>
      <%= link_to 'Back to all trips', trips_path, class: "btn-travel mb-3" %>
    <% elsif ((accepted_applications.count + 1) < @trip.capacity) && @trip.users.exclude?(current_user)%>
      <!-- <%= link_to "Join this trip", new_trip_booking_path(@trip), class: 'btn btn-travel m-5' %> -->
      <button type="button" class="btn btn-travel" data-toggle="modal" data-target="#joinModal">Join this trip</button>
    <% elsif @trip.users.include?(current_user)%>
      <p> You already sent your application to this trip! </p>
      <%= link_to 'Back to all trips', trips_path, class: "btn-travel mb-3" %>
    <% else %>
      <p> This trip is full! </p>
      <%= link_to 'Back to all trips', trips_path, class: "btn-travel mb-3" %>
    <% end %>

  </div>

  <div class="modal fade" id="joinModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Thank you for choosing this trip!</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= simple_form_for [ @trip, @booking ] do |f| %>
            <%= f.input :description, label: "Please tell us why you want to join this trip" %>
            <%= f.submit "Submit your application", class: "btn btn-travel mt-3" %>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/users/_info_window.html.erb
<div class="container-card d-flex text-center align-items-center " style="background-image: url('<%= cl_image_path trip.photo.key %>')">
  <%= link_to trip.title, trip_path(trip) %>
  <%#= cl_image_tag(trip.photo.key, :width=>200 , :height=> 100 , :crop=>"scale") %>
</div>

app/views/users/show.html.erb
<div class = "container mt-3">
<!--   PERSONAL INFO -->
  <div class="bg-white p-4 rounded mb-3 text-center">
    <% if @user.photo.attached? %>
      <p> <%= cl_image_tag @user.photo.key, class: "avatar-dashboard" %> </p>
    <% else %>
      <p> <%= image_tag "https://icon-library.com/images/default-user-icon/default-user-icon-8.jpg", class: "avatar-dashboard" %> </p>
    <% end %>
    <% if @user == current_user %>
      <h3>Welcome <strong><%= @user.first_name %> <%= @user.last_name %></strong></h3>
    <% else %>
      <h3><strong><%= @user.first_name %> <%= @user.last_name %></strong></h3>
    <% end %>
    <p> <%= ((Date.today - @user.birth_date) / 365).to_i %> years old </p>
    <p> <%= @user.description %> </p>
    <a href="#"> <i class="fab fa-instagram"></i> Follow me on instagram</a>
    <% if @user == current_user %>
    <br>
    <%= link_to "Go to dashboard", dashboard_user_path(current_user), class: "btn btn-travel mt-3"%>
    <%= link_to "Edit my profile", edit_user_registration_path(current_user), class: "btn btn-travel-secondary mt-3"%>
    <% end %>
  </div>

  <!--   MAP OF THE WORLD : static for now -->
  <div class="bg-white p-4 rounded mb-3">
    <h3 class= "text-center mb-3"> The <strong>places</strong> I have been to 🌎 </h3>
  <div id="map2"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  </div>